GET http://localhost:9000/api/v1/movies/


###
GET http://localhost:9000/api/v1/movies/65f231289f2196e5c3483071

###
POST http://localhost:9000/api/v1/movies
Content-Type: application/json

{
    "title": "Title example",
    "description": "Description example",
    "completed": false
}

###
PATCH http://localhost:9000/api/v1/movies/65f231289f2196e5c3483071
Content-Type: application/json

{
    "title": "Title Edit",
    "description": "Description Edit",
    "completed": true
}

###
DELETE http://localhost:9000/api/v1/movies/65f231289f2196e5c3483071